export const amenities = {
  accommodation: [
    { key: 'wifi', label: '무선 인터넷' },
    { key: 'parking', label: '주차 가능' },
    { key: 'kitchen', label: '주방' },
    { key: 'washer', label: '세탁기' },
    { key: 'aircon', label: '에어컨' },
    { key: 'tv', label: 'TV' },
    { key: 'hairdryer', label: '헤어드라이어' },
    { key: 'iron', label: '다리미' },
    { key: 'pool', label: '수영장' },
    { key: 'gym', label: '헬스장' },
    { key: 'spa', label: '스파/월풀' },
    { key: 'elevator', label: '엘리베이터' },
    { key: 'breakfast', label: '조식 제공' },
    { key: 'smoking_area', label: '흡연구역' },
    { key: 'non_smoking', label: '금연' },
    { key: 'pets_allowed', label: '반려동물 동반 가능' },
    { key: 'wheelchair_accessible', label: '휠체어 접근 가능' },
  ],
  room: [
    { key: 'room_wifi', label: '객실 내 무선 인터넷' },
    { key: 'room_tv', label: 'TV' },
    { key: 'room_aircon', label: '에어컨' },
    { key: 'room_heating', label: '난방' },
    { key: 'room_refrigerator', label: '냉장고' },
    { key: 'room_minibar', label: '미니바' },
    { key: 'room_hairdryer', label: '헤어드라이어' },
    { key: 'room_iron', label: '다리미' },
    { key: 'room_safe', label: '금고' },
    { key: 'room_desk', label: '업무용 데스크' },
    { key: 'room_balcony_terrace', label: '발코니/테라스' },
    { key: 'room_ocean_view', label: '오션뷰' },
    { key: 'room_city_view', label: '시티뷰' },
    { key: 'room_mountain_view', label: '마운틴뷰' },
    { key: 'room_private_bathroom', label: '개별 욕실' },
    { key: 'room_shared_bathroom', label: '공용 욕실' },
    { key: 'room_bathtub', label: '욕조' },
    { key: 'room_toiletries', label: '욕실용품 (샴푸, 비누 등)' },
    { key: 'room_towels', label: '수건' },
    { key: 'room_kitchenette', label: '간이 주방' },
    { key: 'room_microwave', label: '전자레인지' },
    { key: 'room_coffee_maker', label: '커피 메이커' },
    { key: 'room_soundproof', label: '방음' },
  ],
  // 필요에 따라 다른 타입의 편의시설 추가 가능 (예: common, accessibility 등)
};

export const accommodationTypes = [
  { value: 'HOTEL', label: '호텔' },
  { value: 'MOTEL', label: '모텔' },
  { value: 'PENSION', label: '펜션' },
  { value: 'GUESTHOUSE', label: '게스트하우스' },
  { value: 'RESORT', label: '리조트' },
  { value: 'HANOK', label: '한옥' },
  { value: 'CONDO', label: '콘도' },
  { value: 'APARTMENT', label: '아파트' },
  { value: 'HOUSE', label: '주택 전체' },
  { value: 'CAMPING', label: '캠핑/글램핑' },
  { value: 'OTHER', label: '기타' },
];

export const roomStatuses = [
  { value: 'AVAILABLE', label: '판매중', type: 'success' },
  { value: 'UNAVAILABLE', label: '판매 중지', type: 'info' },
  { value: 'UNDER_MAINTENANCE', label: '점검중', type: 'warning' },
  { value: 'PENDING_DELETION', label: '삭제 대기', type: 'danger' },
]; 